#Template for whenever I refresh the main branch. and even need to re-add the submodules afterwards.

name: Update submodules!

on:
  workflow_dispatch:
    inputs:
      add_sub:
        description: "Add submodule"
        default: ""
        required: false
        type: string
      add_sub_check:
        description: "Add sub check"
        default: false
        required: false
        type: boolean
      add_bundle:
        description: "Add bundle"
        default: "ln -s ../Tweaks/YTABConfig/layout/Library/Application\ Support/YTABConfig.bundle Bundles/YTABConfig.bundle"
        required: false
        type: string
      add_bundle_check:
        description: "Add bundle check"
        default: false
        required: false
        type: boolean
      up_sub_check:
        description: "Update submodule check"
        default: false
        required: false
        type: boolean

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add submodules
        if: ${{ inputs.add_sub_check }}
        run: |
          ${{ inputs.add_sub }}
          git add .
          git commit -m "added submodules"
          git push origin

      - name: Update submodules
        if: ${{ inputs.add_sub_check }}
        run: |
          git submodule update --init --recursive --remote
          git add .
          git commit -m "updated submodules"
          git push origin
        continue-on-error: true

#      - name: Update submodules
#        run: |
#         git submodule update --init --recursive --remote Tweaks/Alderis
#          git add .
#          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTHoldForSpeed
#          git add .
#          git submodule update --init --recursive --remote Tweaks/MrBeastify
#          git add .
#          git submodule update --init --recursive --remote Tweaks/PSHeader
#          git add .
#          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
#          git add .
#          git submodule update --init --recursive --remote Tweaks/uYouLocalization
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTABConfig
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTUHD
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
#          git commit -m "updated submodules"
#          git push origin
#        continue-on-error: true

       - name: Make .bundle files
         if: ${{ inputs.add_bundle_check }}
         run: |
           ${{ inputs.add_bundle }}
           git add .
           git commit -m "Added bundles"
           git push origin

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
