#Template for whenever I refresh the main branch. and even need to re-add the submodules afterwards.

name: Update submodules!

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Add submodules
        run: |
          git fetch
          git pull
          git submodule init
          git submodule add https://github.com/PoomSmart/FLEXing.git Tweaks/FLEXing
          git submodule add https://github.com/dayanch96/uYouLocalization.git Tweaks/uYouLocalization
          git submodule add https://github.com/arichorn/YTHoldForSpeed.git Tweaks/YTHoldForSpeed
          git add .
          git commit -m "added submodules"
          git push origin

#     - name: Update submodules
#       run: |
#         git submodule update --init --recursive --remote
#         git add .
#         git commit -m "updated submodules"
#         git push origin
#       continue-on-error: true

#      - name: Update submodules
#        run: |
#         git submodule update --init --recursive --remote Tweaks/Alderis
#          git add .
#          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTHoldForSpeed
#          git add .
#          git submodule update --init --recursive --remote Tweaks/MrBeastify
#          git add .
#          git submodule update --init --recursive --remote Tweaks/PSHeader
#          git add .
#          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
#          git add .
#          git submodule update --init --recursive --remote Tweaks/uYouLocalization
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTABConfig
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTUHD
#          git add .
#          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
#          git commit -m "updated submodules"
#          git push origin
#        continue-on-error: true

      - name: Make .bundle files
        run: |
          cd Bundles
          ln -s ../Tweaks/uYouLocalization/layout/Library/Application\ Support/uYouLocalization.bundle uYouLocalization.bundle
          ln -s ../Tweaks/YTHoldForSpeed/layout/Library/Application\ Support/YTHoldForSpeed.bundle YTHoldForSpeed.bundle
          git add .
          git commit -m "Added bundles"
          git push origin

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
